### ISSUE TITLE
Hide auto-increasing idMax details

### ISSUE THREAD

**Issue by sarahhh000** [HansiMou/nyu-devops-BankSystem#15]
As a Banker
I need a way to hide auto-increasing idMax details
So that I could be more concentrate on my customer accounts.

Assumptions:
Now Get /accounts returns idMax as an account.
Now it is available to change the idMax using PUT /accounts/idMax

Acceptance Criteria:
When I call the URL /accounts
The idMax is never shown in the account result list:
idMax should never be changed in any way.

**Comment by sarahhh000** [comment]
Actually, if the user accidently changes or deletes idMax, the user might overwrite the previous data, which will cause big chaos.

**Comment by RobinRule** [comment]
User cannot change idmax, not through the existing API . And It's system not user's job to change idMax. And this feature is already implemented in our existing code.

**Comment by RobinRule** [comment]
Sorry about the previous comment... I thought we are talking about let the ID becomes a auto-assigned thing. And you are right, there is no need for this API.

**Comment by sarahhh000** [comment]
As I wrote in assumption part:
It is available to change the idMax using PUT /accounts/idMax
if the user PUT {"idMax" : 0}
there might be chaos here since it might overwrite data in the database.
Even more, the user could delete the idMax key, through the delete method,
then creating a new account can not be achieved.
Thus we need to set access to keep our user away from touching the idMax.

**Comment by RobinRule** [comment]
since when we have the [PUT /accounts/idMax] api...

**Comment by RobinRule** [comment]
but I get your point. Hide idMax information from [GET /accounts] makes sense. My mistake.

**Comment by sarahhh000** [comment]
@app.route('/accounts/<id>', methods=['PUT'])
you know you set idMax as a key in the data base, so it could also be an id for search.
If you are still not convinced, just check GET accounts/, you could find that I delete the idMax.

**Comment by sarahhh000** [comment]
@app.route('/accounts/<id>', methods=['GET'])
you know you set idMax as a key in the data base, so it could also be an id for search.
If you are still not convinced, just check GET accounts/, you could find that I delete the idMax.

**Comment by sarahhh000** [comment]
`@app.route('/accounts/<id>', methods=['GET'])`
you know you set idMax as a key in the data base, so it could also be an id for search.
If you are still not convinced, just check GET accounts/, you could find that I delete the idMax.

**Comment by RobinRule** [comment]
idMax is separate field in database. [PUT /accounts] will not be able to change it. But it is true that [PUT /accounts] method can change id of accounts, and thus may cause an chaos in database. @wangshuangkc , you may need to change your code for this api, make sure id will not be change.
Thanks for point that out.

**Comment by sarahhh000** [comment]
You could try this:
`PUT /accounts/idMax`
`{"idMax": 0}`

**Comment by RobinRule** [comment]
Ha, finally get it! My fault! And sorry for all these trouble I brought. Thanks so much for get me straight about this... Definitely will put this in mind next time. After you pushed your code I will deploy it to cloud as soon as possible.

**Comment by RobinRule** [comment]
Reviewed. Works perfectly. No change need to be made. Code have been deployed.

**Comment by wangshuangkc** [comment]
I have changed the update_account: if the user tries to modify info other than balance, 400_conflict (not sure if this is the correct state"; else the balance will be updated.

**Comment by sarahhh000** [comment]
I use 403 as access forbidden.
Maybe name changing should be allowed.
