### ISSUE TITLE
Create a new account

### ISSUE THREAD

**Issue by HansiMou** [HansiMou/nyu-devops-BankSystem#3]
**As** a Banker
**I need** a way to create a new account
**So that** I can create a new account for new client

**Assumptions**:

Add a URL of /accounts by POST
URL should return the new account
Account ID should be unique

**Acceptance Criteria:**
When I call the URL /accounts by POST
It should show the new account

```
{
  id: <i>
  name: <k>
  balance: <m>
  active: <a>
}
```
Where "id" is the account id, "m" is the balance and "name" is the name, "a" is whether the account is active

**Comment by wangshuangkc** [comment]
why not use exists(id) to check the existence of the key? same to the retrieve function

**Comment by wangshuangkc** [comment]
Actually I do not understand why you do
`for key in redis_server.keys():
            if key == id:`
instead of 
`if redis_server.exists(id)`.
I think the latter one is used for check if the key exists in the db.

**Comment by sarahhh000** [comment]
Guess I just changed to another traverse all accounts method last time...
You are right
The correct usage for checking if an id exists in Redis is
` redis_server.exists(id):`
Fixed it.

**Comment by RobinRule** [comment]
when create a new account, aren't we supposed to assign a globally allocated id to it instead of ask the client to give a id to server?

**Comment by wangshuangkc** [comment]
I think a good is to get the id of the last element, and increment it, but I did not find a way. Thus, is_valid() may not be good for checking the data, as the customer can put just name and balance, and create an account with active = 1 and an auto-generated id.

**Comment by sarahhh000** [comment]
In our current way, we are providing the user of the bank system more power to control client id format. Maybe the user wants to use certain combination of letters and numbers to show more information of the client. Like the current bank systems, customers are assigned specific id which suggests the bank branch which opens the account for the user, maybe city and date and other useful information.

**Comment by RobinRule** [comment]
Not sure about this. Definition of id is more like a system administrator's job. Not banker. If banker are interested in information like city, date. This information should be recorded in database as a separate field, which we don't support yet. Id alone, should be a system allocated unique string to differentiate different account.
