### ISSUE TITLE
Update an account

### ISSUE THREAD

**Issue by HansiMou** [HansiMou/nyu-devops-BankSystem#4]
**As** a Banker
**I need** a way to update an account
**So that** I can do it when client information changed

**Assumptions**:

Add a URL of /accounts/john by PUT
URL should return the new balance of account john.

**Acceptance Criteria:**
When I call the URL /accounts/john
It should return the balance of account john as a JSON string in the format:

```
{
  active: <a>,
  id:<i>
  name: <k>,
  balance: <n>
}
```
Where "n" is the balance, "k" is the name, "i" is the account id, "a" is whether the account is active

**Comment by RobinRule** [comment]
Tested. Work.
