### ISSUE TITLE
Delete an account

### ISSUE THREAD

**Issue by HansiMou** [HansiMou/nyu-devops-BankSystem#5]
**As** a Banker
**I need** a way to delete an account
**So that** I can do it when a client want to destroy his/her account.

**Assumptions**:

Add a URL of /accounts/123
URL should return succeed or not.
After the operation, as long as the account does not exist, then it means it succeed.

**Acceptance Criteria:**
When I call DELETE /accounts/123
Account with ID = 123 is deleted if exists
And always return
```
204-NO_CONTENT
```

**Comment by sarahhh000** [comment]
Professor Rofrano mentioned in class that when DELETE, we should always 
`return '', HTTP_204_NO_CONTENT`

**Comment by wangshuangkc** [comment]
That what I was doubting about. I will modify the story as well later.

**Comment by RobinRule** [comment]
Tested. Work.
