### ISSUE TITLE
Mark the account as inactive/active

### ISSUE THREAD

**Issue by HansiMou** [HansiMou/nyu-devops-BankSystem#7]
**As** a Banker
**I need** a way to mark the account as inactive/active
**So that** I can distinguish active and inactive accounts

**Assumptions**:

Add a URL of /account/john/deactive
URL should return a account marked with inactive
1 means active, and 0 means inactive

**Acceptance Criteria:**
When I call the URL/account/john/deactive
It should return a account marked with inactive

```
{
  name: <n2>,
  balance: 1000,
  active: 0,
  id: <i>
}
```
Where "i" is the account ID and "n2" is the name

**Comment by RobinRule** [comment]
Shouldn't this be more reasonable if we put it in Update a account? Having an action in url is not that restful.
